# Generated by Django 3.2.4 on 2021-07-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguaretecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='product_blank.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
